[package]
name = "runux"
version = "0.1.0"
authors = ["Yusuke Abe <abe@mamorio.jp>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
